# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181221_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='album'),
        ),
    ]
